FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential

ENV PATH=$PATH:/root/bin
ENV LD_LIBRARY_PATH=/root/bin
COPY . /repo
WORKDIR /repo
RUN ./install-debian.sh

FROM ubuntu:20.04 as package
COPY --from=builder /repo/vm/l1vm-nojit /
