FROM --platform=linux/amd64 ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential

ENV PATH=$PATH:/root/bin
ENV LD_LIBRARY_PATH=/root/bin
ADD . /repo
WORKDIR /repo
RUN ./install-debian.sh
